name: Docker Workflow

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: |
          GOOS=linux GOARCH=amd64 go test
          go vet ./...

      - name: Log in to DockerHub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ github.repository }}:latest