name: Docker Workflow

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: |
          GOOS=linux GOARCH=amd64 go test

      - name: Vet
        run: |
          go vet ./...

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ github.repository }}:latest
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Pull Docker image
        run: docker pull ${DOCKER_USERNAME}/${{ github.repository }}

      - name: Stop and remove existing container (if any)
        run: docker stop my-container || true && docker rm my-container || true

      - name: Run Docker container
        run: docker run -d --name my-container -p 8080:8080 ${DOCKER_USERNAME}/${{ github.repository }}:latest        